version: 2

project_name: xpoint-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: xp
    binary: xp
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/pepabo/xpoint-cli/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64
      - goos: windows
        goarch: arm64
    hooks:
      post:
        - cmd: ./scripts/gen-winget-manifest.sh "{{ .Path }}" "{{ .Version }}"
          env:
            - TARGET={{ .Os }}_{{ .Arch }}

archives:
  - formats: [binary]
    name_template: >-
      xp_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  draft: false
  prerelease: auto
  extra_files:
    - glob: ./dist/winget-manifest.yaml
